---
# - name: Determine package manager
#     ansible.builtin.set_fact:
#        package_manager: "{{ 'apt' if ansible_distribution|lower in ['debian', 'ubuntu'] else 'yum' }}"
#
- name: Installing MySQL and Required dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
     - default-mysql-server

- name: Installing python_mysql
  package:
    name: "python3-mysqldb"
    state: present
    update_cache: yes

- name: Start and enable mysql service
  service:
    name: "mysql"
    state: started
    enabled: yes
