---
- name: Install PHP and common extensions
  apt:
    name:
      - php
      - php-fpm
      - php-mysql
      - php-xml
      - php-mbstring
    state: present

# Ensure PHP-FPM is running
- name: Ensure PHP-FPM is running
  service:
    name: php7.4-fpm
    state: started
    enabled: yes
